# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoutubeSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoutubeSample
  pod "youtube-ios-player-helper", "~> 0.1.4"

  target 'YoutubeSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YoutubeSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
